### ISSUE TITLE
RuntimeError: ('Coordinator stopped with threads still running: %s', 'Thread-4 Thread-6 Thread-8')

### ISSUE THREAD

**Issue by icewwn** [ibab/tensorflow-wavenet#17]
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    main()
  File "train.py", line 167, in main
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 325, in join
    " ".join(stragglers))
RuntimeError: ('Coordinator stopped with threads still running: %s', 'Thread-4 Thread-6 Thread-8')

I tried with the solution in http://stackoverflow.com/questions/36210162/tensorflow-stopping-threads-via-coordinator-seems-not-to-work, but now work.

**Comment by icewwn** [comment]
Add "sess.run(queue.close())" before the line "coord.request_stop()" solve the issue.
