### ISSUE TITLE
Error in  '--wav_seed'

### ISSUE THREAD

**Issue by bimahasto** [ibab/tensorflow-wavenet#253]
**When I type the command:**
python generate.py --wav_out_path=./output/music_215.wav  --logdir logdir/generate --wavenet_params wavenet_params.json --save_every 4000 --wav_seed canon_00m_00s__00m_02s.wav --samples 160000 logdir/custom_train/music/2017-04-03T19-35-51/model.ckpt-99999

**Error:** 
Instructions for updating:
Please use tf.global_variables instead.
Restoring model from logdir/custom_train/music/2017-04-03T19-35-51/model.ckpt-99999
Priming generation...
Done.
Traceback (most recent call last):
  File "generate.py", line 279, in <module>
    main()
  File "generate.py", line 213, in main
    window = waveform[-1]
IndexError: list index out of range

**Comment by lemonzi** [comment]
The seed you provided (`canon_00m_00s__00m_02s.wav`) either doesn't exist (wrong path) or is all below the silence threshold. If it's not the path you can tweak `create_seed()`, maybe comment out the silence trimming.
