### ISSUE TITLE
Failure to create logdir?

### ISSUE THREAD

**Issue by delta-6400** [ibab/tensorflow-wavenet#257]
Hello.

I have installed Tensorflow and tested the install - it seems to work fine.  I have installed librosa.  

When I run the test.sh in Cygwin, I do get warnings indicating that initialize_all_variables from tensorflow.python.ops.variables is deprecated and will be removed, and that tf.global_variables_initializer should be used instead, however it does seem to indicate that the WaveNet is learning fine (down to ~ .015 after 300 generations in each of the test cases).

When I try to run the training file, I get the following error.  Could someone point me towards how to resolve this?

```
Using default logdir: ./logdir\train\2017-04-18T20-46-34
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    main()
  File "train.py", line 263, in main
    writer = tf.summary.FileWriter(logdir)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\summary\writer\writer.py
", line 310, in __init__
    filename_suffix)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\summary\writer\event_fil
e_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line
 314, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py
", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ./logdir\train\2017-04-18T20-46-34
```

**Comment by lemonzi** [comment]
The warning is because you are using TensorFlow 1.0 and the pull request that upgrades the code from 0.12 hasn't been merged yet. The error is unrelated; it seems a duplicate of #255.

**Comment by delta-6400** [comment]
Wow can't believe I missed that issue... thanks trying to to specify the log directory now.
