### ISSUE TITLE
Error while training on tf 1.1 TypeError: rmse() got an unexpected keyword argument 'frame_length'

### ISSUE THREAD

**Issue by mathieuarbezhermoso** [ibab/tensorflow-wavenet#258]
Hello !

I recently updated my system to Cuda 8, cudNn 6 and tf 1.1 and now when I'm trying to use train.py I got this error :

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/workshop/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/workshop/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/workshop/DocumentsC1/Learning/Wavenet_Tensorflow_tf1/wavenet/audio_reader.py", line 164, in thread_main
    audio = trim_silence(audio[:, 0], self.silence_threshold)
  File "/media/workshop/DocumentsC1/Learning/Wavenet_Tensorflow_tf1/wavenet/audio_reader.py", line 68, in trim_silence
    energy = librosa.feature.rmse(audio, frame_length=frame_length)
TypeError: rmse() got an unexpected keyword argument 'frame_length'
```

Any fix or idea to go through ? 

I tried the tf1.0 branch but I got the same error. 

Thanks !

**Comment by mathieuarbezhermoso** [comment]
Fixed it by reinstalling librosa 

```
git clone https://github.com/librosa/librosa.git
pip install -e librosa
```

**Comment by lemonzi** [comment]
It seems librosa 0.5 is required (it used to be called `n_fft`, not `frame_length`). Fix is on the way.

**Comment by lemonzi** [comment]
This is now fixed, thanks!
