### ISSUE TITLE
Resource Exhasted Error

### ISSUE THREAD

**Issue by yoyodaman234** [ibab/tensorflow-wavenet#281]
When using `python train.py --data_dir=corpus` Wavenet gives this error multiple times. Each time the amount of memory it lists gets smaller:

```
2017-07-09 11:12:35.288240: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ***************************************************************************************************_
2017-07-09 11:12:35.288277: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[1,1,100000,512]
2017-07-09 11:12:35.291570: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 24.64MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-07-09 11:12:35.291619: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 38.30MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-07-09 11:12:45.291833: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 12.32MiB.  Current allocation summary follows.
```
Each time it gives a long list of thousands of lines like this:
```
2017-07-09 11:02:28.544723: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10206e4cf00 of size 1048576
2017-07-09 11:02:28.544738: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10206f4cf00 of size 524288
2017-07-09 11:02:28.544753: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10206fccf00 of size 2048
2017-07-09 11:02:28.544768: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10206fcd700 of size 1024

```
The last time it gives the error it gives this before dying:
```
2017-07-09 11:02:28.570167: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****************************************************************************************************
2017-07-09 11:02:28.570192: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[64,32,1,1577]
2017-07-09 11:02:28.571510: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2942 get requests, put_count=2240 evicted_count=1000 eviction_rate=0.446429 and unsatisfied allocation rate=0.612508
2017-07-09 11:02:28.571552: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
Storing checkpoint to ./logdir/train/2017-07-09T11-00-41 ... Done.
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    main()
  File "train.py", line 314, in main
    summary, loss_value, _ = sess.run([summaries, loss, optim])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,100000,512]
	 [[Node: wavenet_1/dilated_stack/layer40/add_1 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](wavenet_1/dilated_stack/layer40/skip/Squeeze, wavenet/dilated_stack/layer40/Variable_3/read)]]
	 [[Node: wavenet_1/loss/Mean/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_35221_wavenet_1/loss/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'wavenet_1/dilated_stack/layer40/add_1', defined at:
  File "train.py", line 337, in <module>
    main()
  File "train.py", line 255, in main
    l2_regularization_strength=args.l2_regularization_strength)
  File "/home/joshua/tensorflow-wavenet/wavenet/model.py", line 650, in loss
    raw_output = self._create_network(network_input, gc_embedding)
  File "/home/joshua/tensorflow-wavenet/wavenet/model.py", line 416, in _create_network
    global_condition_batch, output_width)
  File "/home/joshua/tensorflow-wavenet/wavenet/model.py", line 319, in _create_dilation_layer
    skip_contribution = skip_contribution + skip_bias
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 67, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,100000,512]
	 [[Node: wavenet_1/dilated_stack/layer40/add_1 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](wavenet_1/dilated_stack/layer40/skip/Squeeze, wavenet/dilated_stack/layer40/Variable_3/read)]]
	 [[Node: wavenet_1/loss/Mean/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_35221_wavenet_1/loss/Mean", tensor_type=DT_FLOAT, `_device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

In `nvidia-smi` python uses up all available GPU memory while this is happening. It also appears to look for audio files 17 times when it begins:

```
Using default logdir: ./logdir/train/2017-07-09T11-10-58
2017-07-09 11:11:19.969466: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-09 11:11:19.970133: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-09 11:11:19.970148: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-09 11:11:20.285114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1050 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.455
pciBusID 0000:01:00.0
Total memory: 3.94GiB
Free memory: 3.60GiB
2017-07-09 11:11:20.285168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-07-09 11:11:20.285178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-07-09 11:11:20.285192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0)
Trying to restore saved checkpoints from ./logdir/train/2017-07-09T11-10-58 ... No checkpoint found.
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1
files length: 1

```
The corpus I'm training from is one file, 977.1kB in size.

**Comment by devinroth** [comment]
You're clearly running out of memory on your gpu. Lower the sample_size in train.py. 

Devin Roth

**Comment by yoyodaman234** [comment]
Didn't realise it was that simple of a problem, fixed it perfectly. Thanks!
