### ISSUE TITLE
ImportError: libcusolver.

### ISSUE THREAD

**Issue by BLCKPSTV** [ibab/tensorflow-wavenet#297]
Hi,

I'm getting an error while trying to run de training of the wavenet corpus.

```
python train.py --data_dir=file:///home/quinten/Documents/tensorflow-wavenet-master/wav/VCTK-Corpus 
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import tensorflow as tf
  File "/home/quinten/anaconda2/envs/wavenet/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/quinten/anaconda2/envs/wavenet/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/quinten/anaconda2/envs/wavenet/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/quinten/anaconda2/envs/wavenet/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/quinten/anaconda2/envs/wavenet/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/quinten/anaconda2/envs/wavenet/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by gabrielibagon** [comment]
This seems like a Tensorflow/CUDA/CuDNN installation issue (I faced this recently), not anything to do with this repository. You can verify that this is the case by just running `python -c "import tensorflow"` on your command line, and the same error should occur.

If so, I would go through the TF installation steps again, or at least make sure CUDA/CuDNN libraries are correctly located in your %PATH%. I have more information for solving this on Ubuntu (https://stackoverflow.com/questions/43558707/tensorflow-importerror-libcusolver-so-8-0-cannot-open-shared-object-file-no), but this might be a good place to start for Windows: https://www.tensorflow.org/install/install_windows
