### ISSUE TITLE
TypeError whn running train.py

### ISSUE THREAD

**Issue by drdeaton** [ibab/tensorflow-wavenet#350]
When I run train.py, I get the following error:

```
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from wavenet import WaveNetModel, AudioReader, optimizer_factory
  File "/media/dys/Windows/Users/dys/Documents/Coding/Music/tensorflow-wavenet/wavenet/__init__.py", line 2, in <module>
    from .audio_reader import AudioReader
  File "/media/dys/Windows/Users/dys/Documents/Coding/Music/tensorflow-wavenet/wavenet/audio_reader.py", line 7, in <module>
    import librosa
  File "/home/dys/.local/lib/python2.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/dys/.local/lib/python2.7/site-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/dys/.local/lib/python2.7/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/dys/.local/lib/python2.7/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/dys/.local/lib/python2.7/site-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/home/dys/.local/lib/python2.7/site-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/home/dys/.local/lib/python2.7/site-packages/joblib/memory.py", line 847, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer
```
From this, I'm guessing I'm using the wrong version of librosa. What version do you recommend?

**Comment by drdeaton** [comment]
I downgraded to 0.5.0 and still get the same error

**Comment by Masses** [comment]
@Dysproh - I was running into this issue and found this thread: https://github.com/librosa/librosa/issues/732

I was able to solve by running `pip install 'joblib==0.11' --force-reinstall` hopefully that can help you as well

**Comment by Rosehan** [comment]
Same error. have you sloved it ?
