### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by tristankleyn** [ibab/tensorflow-wavenet#405]
Hi, 

I believe there isn't a contrib module in Tensorflow 2.0 - does this mean we need an earlier version of TF to run wavenet?

`import wavenet

2021-10-25 12:32:15.774545: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-25 12:32:15.774629: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):

  File "<ipython-input-1-c506e1f72da2>", line 1, in <module>
    import wavenet

  File "C:\Users\***\***\Environments\project1\lib\site-packages\wavenet\__init__.py", line 5, in <module>
    from .network import Conv, Model, Network

  File "C:\Users\***\***\Environments\project1\lib\site-packages\wavenet\network.py", line 9, in <module>
    from .cell import ConvCell

  File "C:\Users\***\***\Environments\project1\lib\site-packages\wavenet\cell.py", line 6, in <module>
    from tensorflow.contrib.rnn import RNNCell  # pylint: disable=E0611

ModuleNotFoundError: No module named 'tensorflow.contrib'`

Cheers,
Tristan

**Comment by magiccpp** [comment]
you need Python 3.7 , and do following:
pip install tensorflow==1.15.0 librosa==0.6.3 numba==0.48.0 resampy==0.3.1

then you will be fine.
